Installing (updating) the following libraries for your Sagemaker
instance.

In [ ]:
!pip install -U mxnet-cu101mkl==1.6.0  # updating mxnet to at least v1.6


# ドキュメント

この本の長さの制約から、すべてのMXNetの関数とクラスを紹介することはできません (そしてこれを読むみなさんも望んでいないでしょう)。 APIドキュメント、追加のチュートリアルと例は、この本以上に多くのドキュメントを提供します。この節ではMXNet APIを探すための手引を紹介します。


## モジュール内のすべての関数とクラスを探す

どの関数とクラスがモジュール内で呼ばれているかを知るために、`dir`という関数を呼び出します。例えば、`np.random`のモジュールのすべてのプロパティを問い合わせるためには以下を実行します。

In [1]:
from mxnet import np
print(dir(np.random))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_mx_nd_np', 'absolute_import', 'choice', 'multinomial', 'normal', 'rand', 'randint', 'shuffle', 'uniform']


一般に、`__` (Pythonの特殊なオブジェクト) で始まって終わる関数、または単一の `_`で始まる関数 (通常は内部的に利用されている関数) は無視しても構いません。残りの関数/属性名にもとづいて、このモジュールが、一様分布 (`uniform`)、正規分布 (`normal`)、ポアソン分布 (`poisson`) といった乱数を生成する様々なメソッドをもっていることを推定することができます。

## 特定の関数やクラスの利用方法を探す

ある関数やクラスの利用方法について知りたい場合は、`help`関数を利用します。以下の例では、`ndarray`の`ones_like`の関数の使い方を探しています。

In [2]:
help(np.ones_like)

Help on function ones_like in module mxnet.numpy:

ones_like(a)
    Return an array of ones with the same shape and type as a given array.
    
    Parameters
    ----------
    a : ndarray
        The shape and data-type of `a` define these same attributes of
        the returned array.
    
    Returns
    -------
    out : ndarray
        Array of ones with the same shape and type as `a`.
    
    Examples
    --------
    >>> x = np.arange(6)
    >>> x = x.reshape((2, 3))
    >>> x
    array([[0., 1., 2.],
           [3., 4., 5.]])
    >>> np.ones_like(x)
    array([[1., 1., 1.],
           [1., 1., 1.]])
    
    >>> y = np.arange(3, dtype=float)
    >>> y
    array([0., 1., 2.], dtype=float64)
    >>>
    >>> np.ones_like(y)
    array([1., 1., 1.], dtype=float64)



ドキュメントから、 `ones_like`の関数は与えられた`ndarray`と同じshapeの配列を新しく作成し、すべての要素を`1`にセットすることがわかります。可能な場合はいつでも、そのドキュメントに対する理解を確かめるために、手短にテストすることをおすすめします。

In [3]:
x = np.array([[0, 0, 0], [2, 2, 2]])
np.ones_like(x)

array([[1., 1., 1.],
       [1., 1., 1.]])

Jupyter notebookでは、別のウィンドウでドキュメントを表示するために`?`を利用することができます。例えば、`np.random.uniform?`とすれば、それは`help(np.random.uniform)`のコンテンツを、新しいブラウザのウィンドウで表示します。さらに、`np.random.uniform??`のように2つの疑問符を使えば、その関数を実装するコードを表示することができます。

## APIのドキュメント

APIの詳細について知りたい場合は、MXNetのウェブサイト [http://mxnet.apache.org/](http://mxnet.apache.org/) をチェックしてください。適切な見出しのところに詳細を見つけることができるでしょう (そして、Python以外のプログラミング言語についても詳細を見つけられます)。


## まとめ

* 公式のドキュメントは、この書籍以上の説明と例を十分に提供しています。
* `dir` や `help` を呼び出したり、MXNet のウェブサイトを見ることによって、MXNet の API の使い方に関するドキュメントを調べることができます。

## 練習

1. `ones_like`と`autograd`をAPIのドキュメントから探してみましょう。
2. `np.random.choice(4, 2)` を実行した後に、起こりうる全ての出力は何でしょうか。
3. `np.random.choice(4, 2)` を、 `np.random.randint` を使って書き換えることができますか? 

## [議論](https://discuss.mxnet.io/t/2322)

![](../img/qr_lookup-api.svg)